### ISSUE TITLE
Error: Missing compiler for node of type `wikiLink`: `[object Object]`

### ISSUE THREAD

**Issue by linxule** [andymatuschak/note-link-janitor#10]
Thank you for this script!

After run, I see this error message: 

> (node:20403) UnhandledPromiseRejectionWarning: Error: Missing compiler for node of type `wikiLink`: `[object Object]`

Would you be able to help me resolve this? I tried to install remark but the issue persisted

**Comment by andymatuschak** [comment]
Sorry, I can't offer support for this project.

**Comment by linxule** [comment]
Appreciate your resposne! I was able to solve the issue when I import the markdown files via Bear, which somehow fixed the issues.
