### ISSUE TITLE
Markdown link support

### ISSUE THREAD

**Issue by NullSense** [andymatuschak/note-link-janitor#11]
Would it be possible to add standard markdown link support? ([]())

**Comment by andymatuschak** [comment]
Sorry, no; see README:

> This is FYI-style open source. I'm sharing it for interested parties, but without any stewardship commitment. Assume that my default response to issues and pull requests will be to ignore or close them without comment. If you do something interesting with this, though, please let me know.

**Comment by PaulTomchik** [comment]
I was able to get standard markdown links to work like this:

### Before 

```sh
$ cat markdown_link_examples/foo.md 
# Foo Page

See [[Bar Page]]

[foo page]: ./foo.md
[bar page]: ./bar.md
```
```sh
$ cat markdown_link_examples.pre/bar.md
# Bar Page

See [[Foo Page]]

[foo page]: ./foo.md
[bar page]: ./bar.md
```

### Run note-link-janitor

```sh
$  ./node_modules/.bin/note-link-janitor markdown_link_examples
```

### After

```
$ cat markdown_link_examples/foo.md    
# Foo Page

See [[Bar Page]]

[foo page]: ./foo.md
[bar page]: ./bar.md
## Backlinks
* [[Bar Page]]
        * See [[Foo Page]]
```

```sh
$ cat markdown_link_examples/bar.md
# Bar Page

See [[Foo Page]]

[foo page]: ./foo.md
[bar page]: ./bar.md
## Backlinks
* [[Foo Page]]
        * See [[Bar Page]]
```

The links are surrounded with "[" and "]" but the backlinking does work.

![image](https://user-images.githubusercontent.com/3218374/178775597-49c3e77b-3ea0-431f-8735-e8ee956a85b6.png)
