### ISSUE TITLE
Error while running `yarn install`

### ISSUE THREAD

**Issue by tanushbanerjee** [andymatuschak/note-link-janitor#16]
I have run `yarn install` in the terminal and in the source code folder but, it's giving an error:
`error @andymatuschak/note-link-janitor@0.0.1: The engine "node" is incompatible with this module. Expected version ">= 12.0.0". Got "10.23.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

Can someone please help :(
Thank you

**Comment by doxa1062** [comment]
I think you may need to update node: https://nodejs.org/en/download/

**Comment by tanushbanerjee** [comment]
My system is up to date
even Node and NPM

**Comment by andymatuschak** [comment]
You're running Node 10. You need to be running Node 12 or higher.
