### ISSUE TITLE
How to use this script in Bear note?

### ISSUE THREAD

**Issue by forrestchang** [andymatuschak/note-link-janitor#2]
I noticed that your bear has backlinks. Do you use this script to generate that?

![image](https://user-images.githubusercontent.com/7857126/81297936-a080fc00-90a6-11ea-8ee8-8e9f473d7ec0.png)

**Comment by andymatuschak** [comment]
Yes.

**Comment by forrestchang** [comment]
But Bear uses SQLite to store all the notes, there are no markdown files to process.

**Comment by benkogan** [comment]
I believe Andy also uses this script to keep notes in sync with a directory as markdown files: https://github.com/andymatuschak/Bear-Markdown-Export

**Comment by forrestchang** [comment]
@benkogan Thanks, it's very helpful!
