### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by lukesmurray** [andymatuschak/note-link-janitor#6]
Thank you for open sourcing this tool. Do you have any plans to add a license to the repo? I'd like to use some of the ideas in my own project, specifically the nearest block heuristic for adding `context` to backlinks. The package.json says MIT license but I'm not sure if that was an intentional choice or just a default. Cheers.

**Comment by andymatuschak** [comment]
Ah, good nudge; added an MIT `LICENSE` file in #7.
